server {
    listen 80;
    server_name suiteultragym.com www.suiteultragym.com localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Let's Encrypt ACME challenge.
    # Certbot writes challenge files into ./certbot/www on the host,
    # mounted inside this container at /var/www/certbot.
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }
    # API Flask
    # Angular llama /api/... y Nginx lo manda al servicio backend dentro de Docker.
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
    }

    # Angular SPA con hash routing.
    # Mantiene funcionando /#/ruta y recargas del navegador.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
