#docker-compose.yml

services:
  db:
    image: postgres:15 
    restart: unless-stopped
    shm_size: "512mb"
    environment:
      POSTGRES_DB: sistema_tickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Insul1n4
      TZ: America/Tijuana
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./wal-archive:/var/backups/postgres/wal
    networks:
      - backend-net

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      APP_ENV: "prod"

    command: >
      gunicorn
      --workers 3
      --worker-class sync
      --timeout 300
      --graceful-timeout 30
      --keep-alive 5
      --max-requests 1000
      --max-requests-jitter 100
      --access-logfile -
      --error-logfile -
      --capture-output
      -b 0.0.0.0:5000
      app.wsgi:app
    ports:
      - "5000:5000"
      - "127.0.0.1:5901:5901"
    networks:
      - backend-net
    volumes:
      - /home/adminrdp/sistematicketsultra/uploads:/uploads
      - ./backend/.playwright:/app/.playwright



  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - backend-net
    volumes:
      - /home/adminrdp/sistematicketsultra/uploads:/usr/share/nginx/html/uploads:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt:ro


  track-scheduler:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      APP_ENV: "prod"

      WAREHOUSE_RETENTION_HOUR: "1"
      WAREHOUSE_RETENTION_MINUTE: "10"
      WAREHOUSE_RETENTION_DAYS: "7"
      WAREHOUSE_RETENTION_BATCH_LIMIT: "100"
      WAREHOUSE_RETENTION_MAX_BATCHES: "20"

    command: python -m app.warehouse.scheduler.track_scheduler_worker
    restart: unless-stopped
    init: true
    stop_grace_period: 120s
    networks:
      - backend-net
    volumes:
      - /home/adminrdp/sistematicketsultra/uploads:/uploads
    profiles:
      - scheduler
    
  reports-scheduler:
    build:
      context: ./backend
    depends_on:
      - db
    env_file:
      - .env.docker
    environment:
      APP_ENV: "prod"
    command: python -m app.warehouse.scheduler.reports_scheduler_worker
    restart: unless-stopped
    init: true
    stop_grace_period: 120s
    networks:
      - backend-net
    volumes:
      - /home/adminrdp/sistematicketsultra/uploads:/uploads
    profiles:
      - scheduler
volumes:
  postgres_data:

networks:
  backend-net:
