services:
  - type: web
    name: sistema-tickets
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: APP_ENV
        value: prod
      - key: SQLALCHEMY_DATABASE_URI
        value: postgresql+psycopg2://dbultra_cbmd_user:lpYzpRi2UelukjhYjpG45XoK6yPXU8Ps@dpg-d0vr1rripnbc73872240-a.oregon-postgres.render.com/dbultra_cbmd
      - key: SECRET_KEY
        value: R2vYv7BzZghmbDmyiABzX61bTVl8uYo4FCR9f_pZxQvzh0fOY_Aa8b6Qb78pq6ozTo7wFQ
      - key: JWT_SECRET_KEY
        value: XTZqA2kt7J6Zl8jOYW0b_6oH8Nq7KgxT3sP1s5tVxfhGz9qVKsw8JCrLhvPS1ly8kIOhFtQ
      - key: CLOUDINARY_CLOUD_NAME
        value: dmwpxfdck
      - key: CLOUDINARY_API_KEY
        value: "226536834274524"
      - key: CLOUDINARY_API_SECRET
        value: TrxiF3ZYUJBbN4FWHmkI4O7x42o
