services:
  - type: web
    name: sistema-tickets
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app"
    envVars:
      - key: APP_ENV
        value: prod
      - key: SQLALCHEMY_DATABASE_URI
        value: ${SQLALCHEMY_DATABASE_URI}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
      - key: JWT_SECRET_KEY
        value: ${JWT_SECRET_KEY}
      - key: CLOUDINARY_CLOUD_NAME
        value: ${CLOUDINARY_CLOUD_NAME}
      - key: CLOUDINARY_API_KEY
        value: ${CLOUDINARY_API_KEY}
      - key: CLOUDINARY_API_SECRET
        value: ${CLOUDINARY_API_SECRET}
