# app\models\__init__.py

# -------------------------------------------------------------------------------
# MODELOS: Inicialización de Modelos del Sistema
# -------------------------------------------------------------------------------

from .ticket_model import Ticket
from .ticket_attachment import TicketAttachmentORM
from .user_model import UserORM
from .sucursal_model import Sucursal, SucursalOperationalStatus
from .inventario import (
    InventarioGeneral,
    InventarioSucursal,
    MovimientoInventario,
    DetalleMovimiento,
)
from .mantenimiento_equipo import FamiliaEquipoORM, FallaMantenimientoORM
from .departamento_model import Departamento
from .formulario_ticket import FormularioTicket, CampoFormulario
from .pm_bitacora import PmBitacoraORM
from .pm_validacion import PmValidacionORM
from .warehouse import (
    WarehouseSourceORM,
    WarehouseFamilyORM,
    WarehouseOperationalRoleORM,
    WarehouseReportTypeORM,
    WarehouseUploadORM,
    WarehouseOperatorORM,
    WarehouseAuditLogORM,
    KpiDesempenoSnapshotORM,
    KpiDesempenoSnapshotRowORM,
    KpiVentasNuevosSociosSnapshotORM,
    KpiVentasNuevosSociosSnapshotRowORM,
    SociosVencidosSnapshotORM,
    SociosVencidosSnapshotRowORM,
    TrackSourceTiendaDailyORM,
    WarehouseCommercialCatalogORM,
)
from .suite_governance import (
    SuiteRegionORM,
    SuiteSucursalRegionAssignmentORM,
    SuiteRegionManagerORM,
)
from .planning_targets import (
    PlanningModelConfigORM,
    PlanningTargetBatchORM,
    PlanningTargetBranchRowORM,
    PlanningTargetAdjustmentORM,
    PlanningTargetApprovalEventORM,
    PlanningOperatorORM,
)
from .marketing import (
    MarketingMonthlyInputORM,
    MarketingReactivationTariffORM,
    MarketingCampaignV2TariffORM,
    MarketingCampaignV2TariffOverrideORM,
    MarketingCampaignV2BlacklistORM,
    MarketingCampaignV2ChannelBindingORM,
    MarketingCampaignV2TemplateORM,
    MarketingCampaignV2ORM,
    MarketingCampaignV2ProviderCampaignORM,
    MarketingCampaignV2RecipientORM,
    MarketingCampaignV2RecipientDispatchExclusionORM,
    MarketingCampaignV2RecipientEvidenceORM,
    MarketingCampaignV2ProviderStatsSnapshotORM,
    MarketingCampaignV2ProviderRecipientObservationORM,
    MarketingReactivationCampaignORM,
    MarketingReactivationCampaignRecipientORM,
    MarketingIventasSyncRunORM,
    MarketingIventasRawPageORM,
    MarketingIventasContactORM,
    MarketingIventasContactTagORM,
    MarketingMetaSyncRunORM,
    MarketingMetaRawPageORM,
    MarketingMetaAdInsightORM,
)
from .marketing_reactivation_outcome import (
    MarketingReactivationCampaignRecipientOutcomeORM,
)
from .marketing_campaign_delivery import (
    MarketingReactivationCampaignBranchSendORM,
)
from .internal_documents import (
    InternalDocumentCategoryORM,
    InternalDocumentORM,
    InternalDocumentVersionORM,
    InternalDocumentVisibilityORM,
    InternalDocumentLinkORM,
    InternalDocumentAuditLogORM,
    InternalDocumentStatus,
    InternalDocumentVisibilityMode,
    InternalDocumentVisibilityType,
    InternalDocumentLinkEntityType,
    InternalDocumentLinkRole,
    InternalDocumentAuditAction,
    InternalDocumentExternalResourceORM,
    InternalDocumentExternalProvider,
    InternalDocumentExternalResourceKind,
)
from .openings import (
    OpeningAuditAction,
    OpeningAuditLogORM,
    OpeningDependencyType,
    OpeningORM,
    OpeningPhaseORM,
    OpeningPhaseStatus,
    OpeningStatus,
    OpeningTaskCommentORM,
    OpeningTaskDocumentLinkORM,
    OpeningTaskBlockerImpact,
    OpeningTaskBlockerORM,
    OpeningTaskBlockerStatus,
    OpeningTaskBlockerType,
    OpeningTaskDependencyORM,
    OpeningTaskORM,
    OpeningTaskPriority,
    OpeningTaskStatus,
)

from .permissions import (
    PermissionModuleORM,
    PermissionActionORM,
    PermissionRouteMapORM,
)


from .rpa import (
    GascaSmsRequestORM,
    GascaSmsRequestStatus,
)


from .routine_control import (
    RoutineAssignmentEvidenceORM,
    RoutineControlDecisionORM,
    RoutineControlIncidentORM,
    RoutineControlMemberEvidenceORM,
    RoutineControlMemberORM,
    RoutineControlPipelineRunORM,
    RoutineControlProviderRunORM,
)

from .attendance import (
    TrackAttendanceDailyMartORM,
    TrackAttendanceIntervalMartORM,
    WarehouseAttendanceRejectionORM,
    WarehouseAttendanceRunORM,
    WarehouseAttendanceVisitORM,
)

from .system_daily_check import (
    SystemDailyCheckAffectedScope,
    SystemDailyCheckAnswerORM,
    SystemDailyCheckAnswerValue,
    SystemDailyCheckGeneralStatus,
    SystemDailyCheckIssueAttachmentORM,
    SystemDailyCheckIssueORM,
    SystemDailyCheckORM,
    SystemDailyCheckPromptStateORM,
    SystemDailyCheckRolloutBranchORM,
)

from .purchase_requisition import (
    PurchaseRequisitionAttachmentORM,
    PurchaseRequisitionAttachmentType,
    PurchaseRequisitionCategory,
    PurchaseRequisitionEventORM,
    PurchaseRequisitionEventType,
    PurchaseRequisitionFinanceApproverORM,
    PurchaseRequisitionItemORM,
    PurchaseRequisitionNotificationORM,
    PurchaseRequisitionORM,
    PurchaseRequisitionPriority,
    PurchaseRequisitionQuoteFinanceStatus,
    PurchaseRequisitionQuoteORM,
    PurchaseRequisitionReceiptIssueType,
    PurchaseRequisitionReason,
    PurchaseRequisitionStatus,
)

# -------------------------------------------------------------------------------
# EXPORTACIONES: Control de qué modelos estarán disponibles al importar app.models
# -------------------------------------------------------------------------------
__all__ = [
    "Ticket",
    "TicketAttachmentORM",
    "UserORM",
    "Sucursal",
    "InventarioGeneral",
    "InventarioSucursal",
    "MovimientoInventario",
    "DetalleMovimiento",
    "FamiliaEquipoORM",
    "FallaMantenimientoORM",
    "Departamento",
    "FormularioTicket",
    "CampoFormulario",
    "PmBitacoraORM",
    "PmValidacionORM",
    "WarehouseSourceORM",
    "WarehouseFamilyORM",
    "WarehouseOperationalRoleORM",
    "WarehouseReportTypeORM",
    "WarehouseUploadORM",
    "WarehouseOperatorORM",
    "WarehouseAuditLogORM",
    "KpiDesempenoSnapshotORM",
    "KpiDesempenoSnapshotRowORM",
    "KpiVentasNuevosSociosSnapshotORM",
    "KpiVentasNuevosSociosSnapshotRowORM",
    "SociosVencidosSnapshotORM",
    "SociosVencidosSnapshotRowORM",
    "TrackSourceTiendaDailyORM",
    "WarehouseCommercialCatalogORM",
    "SuiteRegionORM",
    "SuiteSucursalRegionAssignmentORM",
    "SuiteRegionManagerORM",
    "PlanningModelConfigORM",
    "PlanningTargetBatchORM",
    "PlanningTargetBranchRowORM",
    "PlanningTargetAdjustmentORM",
    "PlanningTargetApprovalEventORM",
    "PlanningOperatorORM",
    "MarketingMonthlyInputORM",
    "MarketingReactivationTariffORM",
    "MarketingCampaignV2TariffORM",
    "MarketingCampaignV2TariffOverrideORM",
    "MarketingCampaignV2BlacklistORM",
    "MarketingCampaignV2ChannelBindingORM",
    "MarketingCampaignV2TemplateORM",
    "MarketingCampaignV2ORM",
    "MarketingCampaignV2ProviderCampaignORM",
    "MarketingCampaignV2RecipientORM",
    "MarketingCampaignV2RecipientEvidenceORM",
    "MarketingCampaignV2ProviderStatsSnapshotORM",
    "MarketingCampaignV2ProviderRecipientObservationORM",
    "MarketingReactivationCampaignORM",
    "MarketingReactivationCampaignRecipientORM",
    "MarketingReactivationCampaignRecipientOutcomeORM",
    "MarketingReactivationCampaignBranchSendORM",
    "MarketingIventasSyncRunORM",
    "MarketingIventasRawPageORM",
    "MarketingIventasContactORM",
    "MarketingIventasContactTagORM",
    "MarketingMetaSyncRunORM",
    "MarketingMetaRawPageORM",
    "MarketingMetaAdInsightORM",
    "InternalDocumentCategoryORM",
    "InternalDocumentORM",
    "InternalDocumentVersionORM",
    "InternalDocumentVisibilityORM",
    "InternalDocumentLinkORM",
    "InternalDocumentAuditLogORM",
    "InternalDocumentStatus",
    "InternalDocumentVisibilityMode",
    "InternalDocumentVisibilityType",
    "InternalDocumentLinkEntityType",
    "InternalDocumentLinkRole",
    "InternalDocumentAuditAction",
    "InternalDocumentExternalResourceORM",
    "InternalDocumentExternalProvider",
    "InternalDocumentExternalResourceKind",
    "SucursalOperationalStatus",
    "OpeningAuditAction",
    "OpeningAuditLogORM",
    "OpeningDependencyType",
    "OpeningORM",
    "OpeningPhaseORM",
    "OpeningPhaseStatus",
    "OpeningStatus",
    "OpeningTaskDependencyORM",
    "OpeningTaskDocumentLinkORM",
    "OpeningTaskBlockerImpact",
    "OpeningTaskBlockerORM",
    "OpeningTaskBlockerStatus",
    "OpeningTaskBlockerType",
    "OpeningTaskORM",
    "OpeningTaskPriority",
    "OpeningTaskStatus",
    "OpeningTaskCommentORM",
    "PermissionModuleORM",
    "PermissionActionORM",
    "PermissionRouteMapORM",
    "PermissionGrantORM",
    "PermissionGrantAuditLogORM",
    "RoutineAssignmentEvidenceORM",
    "RoutineControlDecisionORM",
    "RoutineControlIncidentORM",
    "RoutineControlMemberEvidenceORM",
    "RoutineControlMemberORM",
    "RoutineControlPipelineRunORM",
    "RoutineControlProviderRunORM",
    "GascaSmsRequestORM",
    "GascaSmsRequestStatus",
    "TrackAttendanceDailyMartORM",
    "TrackAttendanceIntervalMartORM",
    "WarehouseAttendanceRejectionORM",
    "WarehouseAttendanceRunORM",
    "WarehouseAttendanceVisitORM",
    "SystemDailyCheckAffectedScope",
    "SystemDailyCheckAnswerORM",
    "SystemDailyCheckAnswerValue",
    "SystemDailyCheckGeneralStatus",
    "SystemDailyCheckIssueAttachmentORM",
    "SystemDailyCheckIssueORM",
    "SystemDailyCheckORM",
    "SystemDailyCheckPromptStateORM",
    "SystemDailyCheckRolloutBranchORM",
    "PurchaseRequisitionAttachmentORM",
    "PurchaseRequisitionAttachmentType",
    "PurchaseRequisitionCategory",
    "PurchaseRequisitionEventORM",
    "PurchaseRequisitionEventType",
    "PurchaseRequisitionFinanceApproverORM",
    "PurchaseRequisitionItemORM",
    "PurchaseRequisitionNotificationORM",
    "PurchaseRequisitionORM",
    "PurchaseRequisitionPriority",
    "PurchaseRequisitionQuoteFinanceStatus",
    "PurchaseRequisitionQuoteORM",
    "PurchaseRequisitionReceiptIssueType",
    "PurchaseRequisitionReason",
    "PurchaseRequisitionStatus",
]
