from __future__ import annotations

from app.warehouse.services.track_operational_forecast_service import (
    RECENT_DAILY_AVERAGE_METHOD as OPERATIONAL_PROJECTION_METHOD,
    RECENT_DAILY_AVERAGE_METRIC_KEYS as OPERATIONAL_PROJECTION_METRIC_KEYS,
    RECENT_DAILY_AVERAGE_MIN_VALID_DELTAS as OPERATIONAL_PROJECTION_MIN_VALID_DELTAS,
    RECENT_DAILY_AVERAGE_WINDOW_CALENDAR_DAYS as OPERATIONAL_PROJECTION_WINDOW_CALENDAR_DAYS,
    build_recent_daily_average_projection as build_operational_projection,
)


__all__ = [
    "OPERATIONAL_PROJECTION_METHOD",
    "OPERATIONAL_PROJECTION_METRIC_KEYS",
    "OPERATIONAL_PROJECTION_MIN_VALID_DELTAS",
    "OPERATIONAL_PROJECTION_WINDOW_CALENDAR_DAYS",
    "build_operational_projection",
]
