"""Migración inicial

Revision ID: 708ba4302146
Revises: 
Create Date: 2025-08-07 20:16:00.090094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708ba4302146'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_musculares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('horarios_generales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('ciclo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('no_equipo', sa.String(length=50), nullable=True),
    sa.Column('gasto_mes', sa.Integer(), nullable=True),
    sa.Column('pedido_mes', sa.Integer(), nullable=True),
    sa.Column('semana_pedido', sa.String(length=20), nullable=True),
    sa.Column('fecha_inventario', sa.Date(), nullable=True),
    sa.Column('gasto_sem', sa.Integer(), nullable=True),
    sa.Column('grupo_muscular', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marcas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sucursales',
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('sucursal', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sucursal_id')
    )
    op.create_table('tipos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('unidades_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviatura'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('bloques_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('horario_general_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('es_descanso', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['horario_general_id'], ['horarios_generales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogo_clasificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['catalogo_clasificacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reporte', sa.String(length=50), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_general.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('campo_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_campo', sa.String(length=50), nullable=False),
    sa.Column('etiqueta', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('referencia_arbol', sa.Boolean(), nullable=True),
    sa.Column('referencia_inventario', sa.Boolean(), nullable=True),
    sa.Column('solo_si_nivel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario_ticket.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empleado_horario_asignado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('horario_general_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['horario_general_id'], ['horarios_generales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('entrada', 'salida', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registro_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('tipo_marcado', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('asignado_a', sa.String(length=50), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en progreso', 'finalizado', name='estado_ticket_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_finalizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_en_progreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_solucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('historial_fechas', sa.JSON(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('criticidad', sa.Integer(), nullable=False),
    sa.Column('aparato_id', sa.Integer(), nullable=True),
    sa.Column('problema_detectado', sa.Text(), nullable=True),
    sa.Column('necesita_refaccion', sa.Boolean(), nullable=True),
    sa.Column('descripcion_refaccion', sa.Text(), nullable=True),
    sa.Column('url_evidencia', sa.String(length=500), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('equipo', sa.String(length=100), nullable=True),
    sa.Column('clasificacion_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('detalle', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['aparato_id'], ['inventario_general.id'], ),
    sa.ForeignKeyConstraint(['asignado_a'], ['users.username'], ),
    sa.ForeignKeyConstraint(['clasificacion_id'], ['catalogo_clasificacion.id'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_general.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_movimiento')
    op.drop_table('usuarios_permisos')
    op.drop_table('tickets')
    op.drop_table('registro_asistencia')
    op.drop_table('movimientos_inventario')
    op.drop_table('empleado_horario_asignado')
    op.drop_table('campo_formulario')
    op.drop_table('users')
    op.drop_table('inventario_sucursal')
    op.drop_table('formulario_ticket')
    op.drop_table('catalogo_clasificacion')
    op.drop_table('bloques_horario')
    op.drop_table('unidades_medida')
    op.drop_table('tipos_inventario')
    op.drop_table('sucursales')
    op.drop_table('proveedores')
    op.drop_table('marcas')
    op.drop_table('inventario_general')
    op.drop_table('horarios_generales')
    op.drop_table('grupos_musculares')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
