"""Agrega tablas de catálogos

Revision ID: 4fc62cac6df9
Revises: e6b14589471f
Create Date: 2025-07-08 16:06:33.689327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4fc62cac6df9'
down_revision = 'e6b14589471f'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Quitar constraint (antes de eliminar la tabla padre)
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('tickets_aparato_id_fkey', type_='foreignkey')
        # Si ya tienes la nueva relación lista, aquí mismo puedes crear el nuevo FK
        batch_op.create_foreign_key(None, 'inventario_general', ['aparato_id'], ['id'])

    # 2. Ahora sí elimina la tabla dependiente
    op.drop_table('aparatos_gimnasio')
    op.drop_table('migraciones_aplicadas')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tickets_aparato_id_fkey', 'aparatos_gimnasio', ['aparato_id'], ['id'])

    op.create_table('migraciones_aplicadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aplicada_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migraciones_aplicadas_pkey'),
    sa.UniqueConstraint('nombre', name='migraciones_aplicadas_nombre_key')
    )
    op.create_table('aparatos_gimnasio',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sucursal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('marca', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('grupo_muscular', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_equipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], name='aparatos_gimnasio_sucursal_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='aparatos_gimnasio_pkey')
    )
    # ### end Alembic commands ###
