"""Agrega campos gasto_sem, gasto_mes, pedido_mes a InventarioGeneral

Revision ID: 55881cd38892
Revises: ad7df42c0583
Create Date: 2025-07-01 10:29:57.582279

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55881cd38892'
down_revision = 'ad7df42c0583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migraciones_aplicadas')
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gasto_sem', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.drop_column('gasto_sem')

    op.create_table('migraciones_aplicadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aplicada_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migraciones_aplicadas_pkey'),
    sa.UniqueConstraint('nombre', name='migraciones_aplicadas_nombre_key')
    )
    # ### end Alembic commands ###
