"""Migracion inicial para Render

Revision ID: 858f92a81220
Revises: 
Create Date: 2025-06-03 19:54:22.994103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858f92a81220'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.String(length=10), nullable=False),
    sa.Column('sucursal', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('sucursal_id')
    )
    op.create_table('aparatos_gimnasio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('grupo_muscular', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('numero_equipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('entrada', 'salida', name='tipo movimiento_enum'), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('asignado_a', sa.String(length=50), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en progreso', 'finalizado', name='estado_ticket_enum'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_finalizado', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_en_progreso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_solucion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('historial_fechas', sa.JSON(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('criticidad', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=255), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('subsubcategoria', sa.String(length=100), nullable=True),
    sa.Column('aparato_id', sa.Integer(), nullable=True),
    sa.Column('problema_detectado', sa.Text(), nullable=True),
    sa.Column('necesita_refaccion', sa.Boolean(), nullable=True),
    sa.Column('descripcion_refaccion', sa.Text(), nullable=True),
    sa.Column('url_evidencia', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['aparato_id'], ['aparatos_gimnasio.id'], ),
    sa.ForeignKeyConstraint(['asignado_a'], ['users.username'], ),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_movimiento')
    op.drop_table('usuarios_permisos')
    op.drop_table('tickets')
    op.drop_table('movimientos_inventario')
    op.drop_table('users')
    op.drop_table('inventario_sucursal')
    op.drop_table('aparatos_gimnasio')
    op.drop_table('sucursales')
    op.drop_table('productos')
    op.drop_table('departamentos')
    # ### end Alembic commands ###
