"""Migración limpia a inventario general

Revision ID: ad7df42c0583
Revises: 
Create Date: 2025-07-01 09:14:04.990858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad7df42c0583'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aparatos_gimnasio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('grupo_muscular', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('numero_equipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('no_equipo', sa.String(length=50), nullable=True),
    sa.Column('gasto_mes', sa.Integer(), nullable=True),
    sa.Column('pedido_mes', sa.Integer(), nullable=True),
    sa.Column('semana_pedido', sa.String(length=20), nullable=True),
    sa.Column('fecha_inventario', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventario_sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_general.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('entrada', 'salida', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detalle_movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario_general.id'], ),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimientos_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('migraciones_aplicadas')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'aparatos_gimnasio', ['aparato_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('migraciones_aplicadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aplicada_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migraciones_aplicadas_pkey'),
    sa.UniqueConstraint('nombre', name='migraciones_aplicadas_nombre_key')
    )
    op.drop_table('detalle_movimiento')
    op.drop_table('movimientos_inventario')
    op.drop_table('inventario_sucursal')
    op.drop_table('inventario_general')
    op.drop_table('aparatos_gimnasio')
    # ### end Alembic commands ###
