"""Elimina sucursal_id de InventarioGeneral

Revision ID: e6b14589471f
Revises: 55881cd38892
Create Date: 2025-07-04 12:18:33.976124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6b14589471f'
down_revision = '55881cd38892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migraciones_aplicadas')
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.drop_constraint('inventario_general_sucursal_id_fkey', type_='foreignkey')
        batch_op.drop_column('sucursal_id')
        batch_op.drop_column('stock_actual')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_actual', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sucursal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('inventario_general_sucursal_id_fkey', 'sucursales', ['sucursal_id'], ['sucursal_id'])

    op.create_table('migraciones_aplicadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aplicada_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migraciones_aplicadas_pkey'),
    sa.UniqueConstraint('nombre', name='migraciones_aplicadas_nombre_key')
    )
    # ### end Alembic commands ###
