"""add opening task document links

Revision ID: 027af445bc6b
Revises: db19ee809dba
Create Date: 2026-06-12 09:17:00.384103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027af445bc6b'
down_revision = 'db19ee809dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_task_document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_upload_id', sa.Integer(), nullable=False),
    sa.Column('document_role', sa.String(length=80), server_default='EVIDENCE', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('linked_by', sa.Integer(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unlinked_by', sa.Integer(), nullable=True),
    sa.Column('unlinked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['opening_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unlinked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['warehouse_upload_id'], ['warehouse_uploads.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('opening_task_document_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opening_task_document_links_opening_id'), ['opening_id'], unique=False)
        batch_op.create_index('ix_opening_task_document_links_opening_task_status', ['opening_id', 'task_id', 'status'], unique=False)
        batch_op.create_index('ix_opening_task_document_links_task_upload_status', ['task_id', 'warehouse_upload_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_document_links_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_document_links_warehouse_upload_id'), ['warehouse_upload_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_task_document_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_task_document_links_warehouse_upload_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_document_links_task_id'))
        batch_op.drop_index('ix_opening_task_document_links_task_upload_status')
        batch_op.drop_index('ix_opening_task_document_links_opening_task_status')
        batch_op.drop_index(batch_op.f('ix_opening_task_document_links_opening_id'))

    op.drop_table('opening_task_document_links')
    # ### end Alembic commands ###
