"""add opening task comments

Revision ID: 08b732aab9bf
Revises: f94cb18088cb
Create Date: 2026-06-04 11:59:44.306152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b732aab9bf'
down_revision = 'f94cb18088cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_task_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_system_event', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['opening_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opening_task_comments', schema=None) as batch_op:
        batch_op.create_index('idx_opening_task_comments_opening_created', ['opening_id', 'created_at'], unique=False)
        batch_op.create_index('idx_opening_task_comments_task_created', ['task_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_comments_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_comments_is_system_event'), ['is_system_event'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_comments_opening_id'), ['opening_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_comments_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_task_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_task_comments_task_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_comments_opening_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_comments_is_system_event'))
        batch_op.drop_index(batch_op.f('ix_opening_task_comments_created_by'))
        batch_op.drop_index(batch_op.f('ix_opening_task_comments_created_at'))
        batch_op.drop_index('idx_opening_task_comments_task_created')
        batch_op.drop_index('idx_opening_task_comments_opening_created')

    op.drop_table('opening_task_comments')
    # ### end Alembic commands ###
