"""Agregar FK a sucursal_id_destino en tickets con la relacion

Revision ID: 0a698182a7cb
Revises: 2c9828669586
Create Date: 2025-08-08 13:06:13.683903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a698182a7cb'
down_revision = '2c9828669586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id_destino'], ['sucursal_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
