"""InventarioGeneral: agregar categoria_inventario_id (FK a catalogo_categoria_inventario)

Revision ID: 1cf725d0b5bd
Revises: 4f3ed551cd93
Create Date: 2025-08-29 08:23:34.846073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf725d0b5bd'
down_revision = '4f3ed551cd93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_inventario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'catalogo_categoria_inventario', ['categoria_inventario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categoria_inventario_id')

    # ### end Alembic commands ###
