"""add internal document links

Revision ID: 21d6089a97b9
Revises: f57edbdac964
Create Date: 2026-06-03 16:33:35.568933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d6089a97b9'
down_revision = 'f57edbdac964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_document_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_key', sa.String(length=120), nullable=True),
    sa.Column('link_role', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=180), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['internal_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('internal_document_links', schema=None) as batch_op:
        batch_op.create_index('idx_internal_document_links_document_active', ['document_id', 'is_active'], unique=False)
        batch_op.create_index('idx_internal_document_links_entity_id_lookup', ['entity_type', 'entity_id', 'is_active'], unique=False)
        batch_op.create_index('idx_internal_document_links_entity_lookup', ['entity_type', 'entity_key', 'is_active'], unique=False)
        batch_op.create_index('idx_internal_document_links_role_primary', ['link_role', 'is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_entity_key'), ['entity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_link_role'), ['link_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_internal_document_links_updated_by'), ['updated_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('internal_document_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_internal_document_links_updated_by'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_link_role'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_is_primary'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_is_active'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_entity_type'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_entity_key'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_entity_id'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_document_id'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_created_by'))
        batch_op.drop_index(batch_op.f('ix_internal_document_links_created_at'))
        batch_op.drop_index('idx_internal_document_links_role_primary')
        batch_op.drop_index('idx_internal_document_links_entity_lookup')
        batch_op.drop_index('idx_internal_document_links_entity_id_lookup')
        batch_op.drop_index('idx_internal_document_links_document_active')

    op.drop_table('internal_document_links')
    # ### end Alembic commands ###
