"""Agregar campo sucursal_id_destino obligatorio a tickets

Revision ID: 26554a4aecf4
Revises: 708ba4302146
Create Date: 2025-08-08 12:26:58.418020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26554a4aecf4'
down_revision = '708ba4302146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migraciones_aplicadas')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id_destino', sa.Integer(), nullable=True))

    # Actualizar filas existentes con un valor válido
    op.execute('UPDATE tickets SET sucursal_id_destino = 1 WHERE sucursal_id_destino IS NULL')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('sucursal_id_destino', nullable=False)

        # Cambiar aquí la referencia correcta a sucursal_id
        batch_op.create_foreign_key(
            'fk_tickets_sucursal_id_destino',
            'sucursales',
            ['sucursal_id_destino'],
            ['sucursal_id'],  # <-- aquí
            ondelete='CASCADE'
        )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tickets_sucursal_id_destino', type_='foreignkey')
        batch_op.drop_column('sucursal_id_destino')

    # Resto igual
    op.create_table('migraciones_aplicadas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('aplicada_en', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='migraciones_aplicadas_pkey'),
    sa.UniqueConstraint('nombre', name='migraciones_aplicadas_nombre_key')
    )
