"""Inventario: CategoriaInventario jerárquica

Revision ID: 4cb4c3085f54
Revises: 995b3ba7aacd
Create Date: 2025-08-27 08:57:28.617137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb4c3085f54'
down_revision = '995b3ba7aacd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_categoria_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('nivel', sa.Integer(), nullable=False))
        batch_op.drop_constraint('catalogo_categoria_inventario_nombre_key', type_='unique')
        batch_op.create_index('ix_cat_inv_parent', ['parent_id'], unique=False)
        batch_op.create_unique_constraint('uq_cat_inv_nombre_parent', ['nombre', 'parent_id'])
        batch_op.create_foreign_key(None, 'catalogo_categoria_inventario', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogo_categoria_inventario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_cat_inv_nombre_parent', type_='unique')
        batch_op.drop_index('ix_cat_inv_parent')
        batch_op.create_unique_constraint('catalogo_categoria_inventario_nombre_key', ['nombre'])
        batch_op.drop_column('nivel')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
