"""seed permission route map high risk routes

Revision ID: 7b8c9d0e1f2a
Revises: 3d4f6a8b9c10
Create Date: 2026-06-25

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b8c9d0e1f2a"
down_revision = "3d4f6a8b9c10"
branch_labels = None
depends_on = None


EXTRA_ACTIONS = [{'description': 'Operación masiva para eliminar todos los tickets; protegida por admin y bandera '
                 'de entorno.',
  'full_key': 'tickets.delete_all',
  'key': 'delete_all',
  'module_key': 'tickets',
  'name': 'Eliminar todos los tickets',
  'risk_level': 'critical'}]

ROUTE_MAP_ROWS = [{'action_full_key': 'users.manage',
  'current_guard': '_get_current_user_admin',
  'current_scope': 'user_admin',
  'endpoint_function': 'put_sucursales_usuario_admin',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'users',
  'notes': 'module_label=Usuarios / Admin | blueprint=admin_usuarios_bp | csv_action=update | '
           'initial_risk=medium_write | Admin DB-backed; valida payload list/int y reemplaza sucursales asignadas en '
           'transacción. Futuro: validar existencia de sucursales.',
  'review_status': 'ok_hardened',
  'route': '/api/admin/usuarios/<int:user_id>/sucursales',
  'source_file': 'backend/app/routes/admin_usuarios_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'catalog_admin',
  'endpoint_function': 'crear_catalogo',
  'is_active': True,
  'method': 'POST',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación protegida por admin de catálogos; detecta duplicados y usa flujo dedicado para clasificaciones.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/<string:catalogo>',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'catalog_admin',
  'endpoint_function': 'editar_catalogo',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=update | initial_risk=medium_write | Edición '
           'protegida por admin de catálogos; clasificaciones usan flujo dedicado.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/<string:catalogo>/<int:elemento_id>',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'admin_catalog_global',
  'endpoint_function': 'eliminar_catalogo',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=delete | initial_risk=high_delete | Soft '
           'delete cuando existe activo; hard delete requiere ALLOW_CATALOG_HARD_DELETE=true; clasificaciones bloquean '
           'borrado físico.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/<string:catalogo>/<int:elemento_id>',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'catalog_admin',
  'endpoint_function': 'desactivar_clasificacion',
  'is_active': True,
  'method': 'POST',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Desactivación protegida por admin; bloquea clasificaciones con hijos activos.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/clasificaciones/<int:elemento_id>/desactivar',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'catalog_admin',
  'endpoint_function': 'reactivar_clasificacion',
  'is_active': True,
  'method': 'POST',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Reactivación protegida por admin; valida padre activo y duplicados equivalentes.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/clasificaciones/<int:elemento_id>/reactivar',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'catalogs.manage',
  'current_guard': '_validar_admin_catalogos',
  'current_scope': 'admin_catalog_global',
  'endpoint_function': 'importar_catalogo',
  'is_active': True,
  'method': 'POST',
  'module_key': 'catalogs',
  'notes': 'module_label=Catálogos | blueprint=catalogos_bp | csv_action=import | initial_risk=high_job_or_import | '
           'Import masivo protegido por admin; clasificaciones jerárquicas bloqueadas hasta tener validador dedicado.',
  'review_status': 'ok_hardened',
  'route': '/api/catalogos/<string:catalogo>/importar',
  'source_file': 'backend/app/routes/catalogos_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'create_internal_document',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Manager DB-backed vía InternalDocumentUserContext/UserORM.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'update_internal_document_metadata',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=update | '
           'initial_risk=medium_write | Metadata protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'publish_internal_document',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Publicación protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/publish',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'archive_internal_document',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Archivado protegido por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/archive',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'replace_internal_document_version',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Reemplazo de versión protegido por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/versions',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'create_internal_document_link',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Alta de link protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/links',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'update_internal_document_link',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=update | '
           'initial_risk=medium_write | Edición de link protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/links/<int:link_id>',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'deactivate_internal_document_link',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=delete | '
           'initial_risk=medium_write | Desactivación de link protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/links/<int:link_id>',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'create_internal_document_external_resource',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Alta de recurso externo protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/external-resources',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'internal_documents.manage',
  'current_guard': 'require_internal_document_manager',
  'current_scope': 'internal_documents_manager',
  'endpoint_function': 'update_internal_document_visibility',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=internal_documents_bp | csv_action=update | '
           'initial_risk=medium_write | Gestión de visibilidad protegida por manager DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/internal-documents/<int:document_id>/visibility',
  'source_file': 'backend/app/routes/internal_documents_routes.py'},
 {'action_full_key': 'inventory.master_write',
  'current_guard': '_require_inventory_global_write',
  'current_scope': 'inventory_global_write',
  'endpoint_function': 'crear_inventario',
  'is_active': True,
  'method': 'POST',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=create/execute | initial_risk=medium_write '
           '| Creación de inventario maestro protegida por roles globales de inventario.',
  'review_status': 'ok_hardened',
  'route': '/api/inventario/',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'inventory.movement_write',
  'current_guard': '_require_inventory_movement_write',
  'current_scope': 'inventory_movement_branch_scope',
  'endpoint_function': 'registrar_movimiento',
  'is_active': True,
  'method': 'POST',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=create/execute | initial_risk=medium_write '
           '| Movimiento protegido por scope de sucursal/rol. Usa usuario actual real, no usuario_id del payload.',
  'review_status': 'ok_hardened',
  'route': '/api/inventario/movimientos',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'inventory.master_write',
  'current_guard': '_require_inventory_global_write',
  'current_scope': 'inventory_global_write',
  'endpoint_function': 'editar_inventario',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=update | initial_risk=medium_write | '
           'Edición de inventario maestro protegida por roles globales de inventario.',
  'review_status': 'ok_hardened',
  'route': '/api/inventario/<int:inventario_id>',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'inventory.master_write',
  'current_guard': '_require_inventory_global_write',
  'current_scope': 'inventory_global_write',
  'endpoint_function': 'eliminar_inventario',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=delete | initial_risk=high_delete | Guard '
           'correcto. Hard delete permitido si no hay movimientos; evaluar soft delete/env gate/auditoría futura.',
  'review_status': 'needs_manual_decision',
  'route': '/api/inventario/<int:inventario_id>',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'inventory.movement_write',
  'current_guard': '_require_inventory_movement_write',
  'current_scope': 'inventory_movement_branch_scope',
  'endpoint_function': 'eliminar_movimiento',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=delete | initial_risk=high_delete | Guard '
           'correcto. Revierte stock y borra histórico; evaluar cancelación/reverso auditado.',
  'review_status': 'needs_manual_decision',
  'route': '/api/inventario/movimientos/<int:id>',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'inventory.master_write',
  'current_guard': '_require_inventory_global_write',
  'current_scope': 'inventory_global_write',
  'endpoint_function': 'importar_inventario',
  'is_active': True,
  'method': 'POST',
  'module_key': 'inventory',
  'notes': 'module_label=Inventario | blueprint=inventario_bp | csv_action=import | initial_risk=high_job_or_import | '
           'Guard correcto. Import masivo directo a InventarioGeneral; evaluar deduplicación, validación fuerte, '
           'auditoría/import batch y rollback controlado.',
  'review_status': 'needs_manual_decision',
  'route': '/api/inventario/importar',
  'source_file': 'backend/app/routes/inventarios.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'create_opening',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de apertura protegida por admin y auditada.',
  'review_status': 'ok_hardened',
  'route': '/api/openings',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'update_opening',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=update | initial_risk=medium_write | Edición '
           'de apertura protegida por admin y auditada.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'create_opening_phase',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de fase protegida por admin y auditada.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/phases',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'update_opening_phase',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=update | initial_risk=medium_write | Edición '
           'de fase protegida por admin; valida pertenencia a apertura y audita cambios.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/phases/<int:phase_id>',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'create_opening_task',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de tarea protegida por admin; valida pertenencia y audita creación.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/tasks',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'update_opening_task',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=update | initial_risk=medium_write | Edición '
           'de tarea protegida por admin; valida pertenencia y audita cambios.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/tasks/<int:task_id>',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'create_task_dependency',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de dependencia protegida por admin; valida pertenencia y evita autodependencia.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/tasks/<int:task_id>/dependencies',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'delete_task_dependency',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=delete | initial_risk=high_delete | Valida '
           'apertura/dependencia y registra auditoría TASK_DEPENDENCY_DELETED.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/task-dependencies/<int:dependency_id>',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'create_task_blocker',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de bloqueo protegida por admin; valida pertenencia, duplicados y audita creación.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/tasks/<int:task_id>/blockers',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'resolve_task_blocker',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=update | initial_risk=medium_write | '
           'Resolución de bloqueo protegida por admin; valida pertenencia y audita resolución.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/task-blockers/<int:blocker_id>/resolve',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.manage',
  'current_guard': '_require_openings_admin',
  'current_scope': 'openings_admin',
  'endpoint_function': 'upload_task_document',
  'is_active': True,
  'method': 'POST',
  'module_key': 'internal_documents',
  'notes': 'module_label=Nube Corporativa | blueprint=openings_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Upload documental en Aperturas protegido por rol DB-backed y '
           'OPENINGS_ADMIN_ROLES.',
  'review_status': 'ok_hardened',
  'route': '/api/openings/<int:opening_id>/tasks/<int:task_id>/documents/upload',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'openings.comment',
  'current_guard': '_require_openings_read',
  'current_scope': 'openings_read_comment_policy',
  'endpoint_function': 'create_task_comment',
  'is_active': True,
  'method': 'POST',
  'module_key': 'openings',
  'notes': 'module_label=Aperturas | blueprint=openings_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Es write real, pero usa guard de lectura. Puede ser intencional como colaboración; decidir si comentar '
           'requiere permiso específico.',
  'review_status': 'needs_manual_decision',
  'route': '/api/openings/<int:opening_id>/tasks/<int:task_id>/comments',
  'source_file': 'backend/app/routes/openings_routes.py'},
 {'action_full_key': 'users.manage',
  'current_guard': '_require_permisos_admin',
  'current_scope': 'legacy_permissions_admin',
  'endpoint_function': 'asignar_permiso',
  'is_active': True,
  'method': 'POST',
  'module_key': 'reports',
  'notes': 'module_label=General / Otro | blueprint=permisos_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Asignación de permiso legacy protegida por admin DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/permisos/asignar',
  'source_file': 'backend/app/routes/permisos_routes.py'},
 {'action_full_key': 'users.manage',
  'current_guard': '_require_permisos_admin',
  'current_scope': 'legacy_permissions_admin',
  'endpoint_function': 'eliminar_permiso',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'reports',
  'notes': 'module_label=General / Otro | blueprint=permisos_bp | csv_action=delete | initial_risk=high_delete | '
           'Borrado de permiso legacy protegido por admin DB-backed.',
  'review_status': 'ok_hardened',
  'route': '/api/permisos/eliminar',
  'source_file': 'backend/app/routes/permisos_routes.py'},
 {'action_full_key': 'planning.configure_model',
  'current_guard': 'require_planning_model_config',
  'current_scope': 'planning_operator_can_configure_model',
  'endpoint_function': 'create_model_config_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Usa PlanningOperatorORM activo con can_configure_model.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/model-configs',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.approve',
  'current_guard': 'require_planning_approve',
  'current_scope': 'planning_operator_can_approve',
  'endpoint_function': 'approve_target_batch_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Usa PlanningOperatorORM activo con can_approve.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/approve',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.approve',
  'current_guard': 'require_planning_approve',
  'current_scope': 'planning_operator_can_approve',
  'endpoint_function': 'reject_target_batch_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Usa PlanningOperatorORM activo con can_approve para aprobar/rechazar.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/reject',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.publish',
  'current_guard': 'require_planning_publish',
  'current_scope': 'planning_operator_can_publish',
  'endpoint_function': 'publish_approved_batch_to_track_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Publicación hacia Track protegida por PlanningOperatorORM activo con '
           'can_publish.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/publish',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.edit',
  'current_guard': 'require_planning_edit',
  'current_scope': 'planning_operator_can_edit',
  'endpoint_function': 'create_target_batch_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Creación de batch protegida por PlanningOperatorORM activo con can_edit.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.edit',
  'current_guard': 'require_planning_edit',
  'current_scope': 'planning_operator_can_edit',
  'endpoint_function': 'add_branch_row_to_batch_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Alta de fila por sucursal protegida por PlanningOperatorORM activo con '
           'can_edit.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/branch-rows',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.edit',
  'current_guard': 'require_planning_edit',
  'current_scope': 'planning_operator_can_edit',
  'endpoint_function': 'update_branch_row_in_batch_route',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=update | '
           'initial_risk=medium_write | Edición de fila por sucursal protegida por PlanningOperatorORM activo con '
           'can_edit.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/branch-rows/<int:branch_row_id>',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'planning.submit',
  'current_guard': 'require_planning_submit',
  'current_scope': 'planning_operator_can_submit',
  'endpoint_function': 'submit_target_batch_route',
  'is_active': True,
  'method': 'POST',
  'module_key': 'planning',
  'notes': 'module_label=Planning / Metas | blueprint=planning_targets_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Envío a revisión protegido por PlanningOperatorORM activo con can_submit.',
  'review_status': 'ok_hardened',
  'route': '/api/planning/targets/batches/<int:batch_id>/submit',
  'source_file': 'backend/app/routes/planning_targets_routes.py'},
 {'action_full_key': 'pm.execute',
  'current_guard': 'require_pm_execute + branch_scope',
  'current_scope': 'pm_execute_branch_scope',
  'endpoint_function': 'pm_mobile_crear_bitacora',
  'is_active': True,
  'method': 'POST',
  'module_key': 'pm',
  'notes': 'module_label=PM | blueprint=pm_bp | csv_action=create/execute | initial_risk=medium_write | Creación de '
           'bitácora protegida por permiso de ejecución y validación de sucursal.',
  'review_status': 'ok_hardened',
  'route': '/api/pm/mobile/bitacoras',
  'source_file': 'backend/app/routes/pm_routes.py'},
 {'action_full_key': 'pm.execute',
  'current_guard': 'require_pm_execute + branch_scope',
  'current_scope': 'pm_execute_branch_scope',
  'endpoint_function': 'pm_preventivo_registrar',
  'is_active': True,
  'method': 'POST',
  'module_key': 'pm',
  'notes': 'module_label=PM | blueprint=pm_bp | csv_action=create/execute | initial_risk=medium_write | Registro '
           'preventivo protegido por permiso de ejecución y validación de sucursal.',
  'review_status': 'ok_hardened',
  'route': '/api/pm/preventivo/registrar',
  'source_file': 'backend/app/routes/pm_routes.py'},
 {'action_full_key': 'pm.validate',
  'current_guard': 'require_pm_validate',
  'current_scope': 'pm_validate',
  'endpoint_function': 'pm_crear_validacion',
  'is_active': True,
  'method': 'POST',
  'module_key': 'pm',
  'notes': 'module_label=PM | blueprint=pm_bp | csv_action=create/execute | initial_risk=medium_write | Validación '
           'protegida por permiso dedicado; evita doble validación y auto-validación.',
  'review_status': 'ok_hardened',
  'route': '/api/pm/validaciones',
  'source_file': 'backend/app/routes/pm_routes.py'},
 {'action_full_key': 'pm.configure',
  'current_guard': 'require_pm_configure + branch_scope',
  'current_scope': 'pm_configure_branch_scope',
  'endpoint_function': 'pm_crear_configuracion',
  'is_active': True,
  'method': 'POST',
  'module_key': 'pm',
  'notes': 'module_label=PM | blueprint=pm_bp | csv_action=create/execute | initial_risk=medium_write | Creación de '
           'configuración protegida por permiso de configuración y validación de sucursal.',
  'review_status': 'ok_hardened',
  'route': '/api/pm/configuraciones',
  'source_file': 'backend/app/routes/pm_routes.py'},
 {'action_full_key': 'pm.configure',
  'current_guard': 'require_pm_configure + branch_scope',
  'current_scope': 'pm_configure_branch_scope',
  'endpoint_function': 'pm_actualizar_configuracion',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'pm',
  'notes': 'module_label=PM | blueprint=pm_bp | csv_action=update | initial_risk=medium_write | Actualización de '
           'configuración protegida por permiso de configuración y validación de sucursal.',
  'review_status': 'ok_hardened',
  'route': '/api/pm/configuraciones/<int:config_id>',
  'source_file': 'backend/app/routes/pm_routes.py'},
 {'action_full_key': 'reports.create_error_report',
  'current_guard': 'jwt_required',
  'current_scope': 'authenticated_bug_report',
  'endpoint_function': 'reportar_error',
  'is_active': True,
  'method': 'POST',
  'module_key': 'reports',
  'notes': 'module_label=Reportes | blueprint=reportes_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Reporte de bug permitido a usuarios autenticados; crea ticket asociado al usuario real.',
  'review_status': 'ok_hardened',
  'route': '/api/reportes/reportar-error',
  'source_file': 'backend/app/routes/reportes.py'},
 {'action_full_key': 'tickets.create',
  'current_guard': 'jwt_required',
  'current_scope': 'authenticated_ticket_creation',
  'endpoint_function': 'create_ticket',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Creación de tickets requiere sesión autenticada. Flujo activo no modificado.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/create',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.update_status',
  'current_guard': 'jwt_required + bloquea_lectores_globales + filtrar_tickets_por_usuario',
  'current_scope': 'ticket_visibility_scope',
  'endpoint_function': 'update_ticket_status',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=update | initial_risk=medium_write | Valida acceso '
           'al ticket mediante filtrar_tickets_por_usuario(actor).',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/update/<int:id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.update',
  'current_guard': '_require_ticket_admin_action',
  'current_scope': 'ticket_admin',
  'endpoint_function': 'migrar_historial_local',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Operación administrativa protegida por admin de tickets.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/migrar-historial-local',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.delete_all',
  'current_guard': '_require_ticket_admin_action + ALLOW_TICKET_DELETE_ALL',
  'current_scope': 'ticket_admin_env_gated',
  'endpoint_function': 'eliminar_todos_los_tickets',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=delete | initial_risk=high_delete | Operación '
           'masiva bloqueada salvo bandera explícita.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/eliminar-todos',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.notify',
  'current_guard': 'jwt_required + filtrar_tickets_por_usuario',
  'current_scope': 'ticket_visibility_scope',
  'endpoint_function': 'notify_ticket',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Valida acceso al ticket mediante filtrar_tickets_por_usuario(user).',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/notify/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': None,
  'current_guard': 'removed',
  'current_scope': 'removed',
  'endpoint_function': 'rrhh_solicitar',
  'is_active': False,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Endpoint RRHH fuera del flujo actual; removido de backend.',
  'review_status': 'decommissioned',
  'route': '/api/tickets/rrhh/solicitar/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': None,
  'current_guard': 'removed',
  'current_scope': 'removed',
  'endpoint_function': 'rrhh_aprobar',
  'is_active': False,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Endpoint RRHH fuera del flujo actual; removido de backend.',
  'review_status': 'decommissioned',
  'route': '/api/tickets/rrhh/aprobar/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': None,
  'current_guard': 'removed',
  'current_scope': 'removed',
  'endpoint_function': 'rrhh_rechazar',
  'is_active': False,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Endpoint RRHH fuera del flujo actual; removido de backend.',
  'review_status': 'decommissioned',
  'route': '/api/tickets/rrhh/rechazar/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.update',
  'current_guard': 'jwt_required',
  'current_scope': 'ticket_operational_flow',
  'endpoint_function': 'set_compromiso',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=update | initial_risk=medium_write | Ruta activa '
           'de compromiso de solución/refacción. Mantiene lógica funcional existente.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/compromiso/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.close',
  'current_guard': 'jwt_required + bloquea_lectores_globales + _puede_cerrar_ticket_desde_cero',
  'current_scope': 'admin_or_ticket_branch_manager',
  'endpoint_function': 'cierre_gerente_desde_cero',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Cierre administrativo protegido por admin o gerente de sucursal destino.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/cierre/gerente-desde-cero/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.close',
  'current_guard': 'jwt_required',
  'current_scope': 'active_ticket_closure_flow',
  'endpoint_function': 'cierre_solicitar',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | Ruta '
           'activa de solicitud de cierre; flujo de cierre no modificado.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/cierre/solicitar/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.close',
  'current_guard': 'jwt_required',
  'current_scope': 'active_ticket_closure_flow',
  'endpoint_function': 'cierre_rechazar_jefe',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | Ruta '
           'activa de rechazo por jefe/departamento; flujo de cierre no modificado.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/cierre/rechazar-jefe/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.close',
  'current_guard': 'jwt_required',
  'current_scope': 'active_ticket_creator_closure_flow',
  'endpoint_function': 'cierre_aceptar_creador',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | Ruta '
           'activa de aceptación por creador; flujo de cierre no modificado.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/cierre/aceptar-creador/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'tickets.close',
  'current_guard': 'jwt_required',
  'current_scope': 'active_ticket_creator_closure_flow',
  'endpoint_function': 'cierre_rechazar_creador',
  'is_active': True,
  'method': 'POST',
  'module_key': 'tickets',
  'notes': 'module_label=Tickets | blueprint=ticket_bp | csv_action=create/execute | initial_risk=medium_write | Ruta '
           'activa de rechazo por creador; flujo de cierre no modificado.',
  'review_status': 'ok_hardened',
  'route': '/api/tickets/cierre/rechazar-creador/<int:ticket_id>',
  'source_file': 'backend/app/routes/ticket_routes.py'},
 {'action_full_key': 'track.run_daily_pipeline',
  'current_guard': '_require_track_admin_role',
  'current_scope': 'track_admin',
  'endpoint_function': 'run_track_daily_pipeline_endpoint',
  'is_active': True,
  'method': 'POST',
  'module_key': 'track',
  'notes': 'module_label=Track / BI | blueprint=track_bp | csv_action=run_job | initial_risk=high_job_or_import | '
           'Admin-only; valida fecha/modo y bloquea ejecución para fechas pasadas desde este flujo.',
  'review_status': 'ok_hardened',
  'route': '/api/track/run-daily-pipeline',
  'source_file': 'backend/app/routes/track_routes.py'},
 {'action_full_key': 'track.run_agregadoras',
  'current_guard': '_require_track_admin_role',
  'current_scope': 'track_admin',
  'endpoint_function': 'run_track_agregadoras_integration_endpoint',
  'is_active': True,
  'method': 'POST',
  'module_key': 'track',
  'notes': 'module_label=Track / BI | blueprint=track_bp | csv_action=run_job | initial_risk=high_job_or_import | '
           'Admin-only; integración manual de agregadoras para la fecha solicitada.',
  'review_status': 'ok_hardened',
  'route': '/api/track/run-agregadoras-integration',
  'source_file': 'backend/app/routes/track_routes.py'},
 {'action_full_key': 'users.manage',
  'current_guard': '_require_admin',
  'current_scope': 'user_admin',
  'endpoint_function': 'crear_usuario',
  'is_active': True,
  'method': 'POST',
  'module_key': 'users',
  'notes': 'module_label=Usuarios / Admin | blueprint=usuarios_bp | csv_action=create/execute | '
           'initial_risk=medium_write | Guard correcto. Permite crear cualquier rol/sucursal/departamento; futuro: '
           'política granular de roles altos y catálogo de roles permitidos.',
  'review_status': 'needs_manual_decision',
  'route': '/api/usuarios',
  'source_file': 'backend/app/routes/usuarios_routes.py'},
 {'action_full_key': 'users.manage',
  'current_guard': '_require_admin',
  'current_scope': 'user_admin',
  'endpoint_function': 'editar_usuario',
  'is_active': True,
  'method': 'PUT',
  'module_key': 'users',
  'notes': 'module_label=Usuarios / Admin | blueprint=usuarios_bp | csv_action=update | initial_risk=medium_write | '
           'Guard correcto. Permite modificar rol/sucursal/departamento/password/email; futuro: política granular para '
           'cambios sensibles y autoedición.',
  'review_status': 'needs_manual_decision',
  'route': '/api/usuarios/<int:user_id>',
  'source_file': 'backend/app/routes/usuarios_routes.py'},
 {'action_full_key': 'users.manage',
  'current_guard': '_require_admin + ALLOW_USER_HARD_DELETE',
  'current_scope': 'user_admin_env_gated',
  'endpoint_function': 'eliminar_usuario',
  'is_active': True,
  'method': 'DELETE',
  'module_key': 'users',
  'notes': 'module_label=Usuarios / Admin | blueprint=usuarios_bp | csv_action=delete | initial_risk=high_delete | '
           'Hard delete bloqueado salvo bandera explícita; bloquea self-delete.',
  'review_status': 'ok_hardened',
  'route': '/api/usuarios/<int:user_id>',
  'source_file': 'backend/app/routes/usuarios_routes.py'},
 {'action_full_key': 'warehouse.upload',
  'current_guard': 'require_warehouse_upload',
  'current_scope': 'warehouse_operator_can_upload',
  'endpoint_function': 'warehouse_create_upload',
  'is_active': True,
  'method': 'POST',
  'module_key': 'warehouse',
  'notes': 'module_label=Warehouse | blueprint=warehouse_bp | csv_action=create/execute | initial_risk=medium_write | '
           'Guard correcto con WarehouseOperatorORM y can_upload. Futuro: agregar is_active o política formal de '
           'desactivación de operador.',
  'review_status': 'needs_manual_decision',
  'route': '/api/warehouse/uploads',
  'source_file': 'backend/app/routes/warehouse_routes.py'},
 {'action_full_key': 'warehouse.archive',
  'current_guard': 'require_warehouse_archive',
  'current_scope': 'warehouse_operator_can_archive',
  'endpoint_function': 'warehouse_archive_upload',
  'is_active': True,
  'method': 'PATCH',
  'module_key': 'warehouse',
  'notes': 'module_label=Warehouse | blueprint=warehouse_bp | csv_action=update | initial_risk=medium_write | Guard '
           'correcto con WarehouseOperatorORM y can_archive. Futuro: agregar is_active o política formal de '
           'desactivación de operador.',
  'review_status': 'needs_manual_decision',
  'route': '/api/warehouse/uploads/<int:upload_id>/archive',
  'source_file': 'backend/app/routes/warehouse_routes.py'}]


def _scalar_or_none(bind, statement, params):
    return bind.execute(sa.text(statement), params).scalar()


def upgrade():
    bind = op.get_bind()

    for action in EXTRA_ACTIONS:
        module_id = _scalar_or_none(
            bind,
            "SELECT id FROM permission_modules WHERE key = :module_key",
            {"module_key": action["module_key"]},
        )

        if module_id is None:
            raise RuntimeError(f"Permission module not found: {action['module_key']}")

        bind.execute(
            sa.text(
                """
                INSERT INTO permission_actions (
                    module_id,
                    key,
                    full_key,
                    name,
                    description,
                    risk_level,
                    is_active,
                    created_at,
                    updated_at
                )
                VALUES (
                    :module_id,
                    :key,
                    :full_key,
                    :name,
                    :description,
                    :risk_level,
                    true,
                    now(),
                    now()
                )
                ON CONFLICT (full_key) DO UPDATE SET
                    key = EXCLUDED.key,
                    name = EXCLUDED.name,
                    description = EXCLUDED.description,
                    risk_level = EXCLUDED.risk_level,
                    is_active = true,
                    updated_at = now()
                """
            ),
            {
                "module_id": module_id,
                "key": action["key"],
                "full_key": action["full_key"],
                "name": action["name"],
                "description": action["description"],
                "risk_level": action["risk_level"],
            },
        )

    for row in ROUTE_MAP_ROWS:
        module_id = _scalar_or_none(
            bind,
            "SELECT id FROM permission_modules WHERE key = :module_key",
            {"module_key": row["module_key"]},
        )

        if module_id is None:
            raise RuntimeError(f"Permission module not found: {row['module_key']}")

        action_id = None
        if row.get("action_full_key"):
            action_id = _scalar_or_none(
                bind,
                "SELECT id FROM permission_actions WHERE full_key = :full_key",
                {"full_key": row["action_full_key"]},
            )

            if action_id is None:
                raise RuntimeError(f"Permission action not found: {row['action_full_key']}")

        bind.execute(
            sa.text(
                """
                INSERT INTO permission_route_map (
                    method,
                    route,
                    endpoint_function,
                    source_file,
                    module_id,
                    action_id,
                    current_guard,
                    current_scope,
                    review_status,
                    notes,
                    is_active,
                    created_at,
                    updated_at
                )
                VALUES (
                    :method,
                    :route,
                    :endpoint_function,
                    :source_file,
                    :module_id,
                    :action_id,
                    :current_guard,
                    :current_scope,
                    :review_status,
                    :notes,
                    :is_active,
                    now(),
                    now()
                )
                ON CONFLICT (method, route, endpoint_function) DO UPDATE SET
                    source_file = EXCLUDED.source_file,
                    module_id = EXCLUDED.module_id,
                    action_id = EXCLUDED.action_id,
                    current_guard = EXCLUDED.current_guard,
                    current_scope = EXCLUDED.current_scope,
                    review_status = EXCLUDED.review_status,
                    notes = EXCLUDED.notes,
                    is_active = EXCLUDED.is_active,
                    updated_at = now()
                """
            ),
            {
                "method": row["method"],
                "route": row["route"],
                "endpoint_function": row["endpoint_function"],
                "source_file": row["source_file"],
                "module_id": module_id,
                "action_id": action_id,
                "current_guard": row["current_guard"],
                "current_scope": row["current_scope"],
                "review_status": row["review_status"],
                "notes": row["notes"],
                "is_active": row["is_active"],
            },
        )


def downgrade():
    bind = op.get_bind()

    for row in ROUTE_MAP_ROWS:
        bind.execute(
            sa.text(
                """
                DELETE FROM permission_route_map
                WHERE method = :method
                  AND route = :route
                  AND endpoint_function = :endpoint_function
                """
            ),
            {
                "method": row["method"],
                "route": row["route"],
                "endpoint_function": row["endpoint_function"],
            },
        )

    for action in EXTRA_ACTIONS:
        bind.execute(
            sa.text(
                """
                DELETE FROM permission_actions
                WHERE full_key = :full_key
                """
            ),
            {"full_key": action["full_key"]},
        )
