"""ticket flujos rrhh + doble check

Revision ID: a91dc3515ae9
Revises: 1cf725d0b5bd
Create Date: 2025-09-24 09:13:41.709752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91dc3515ae9'
down_revision = '1cf725d0b5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.drop_index('idx_inv_gen_cat_nombre')

    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.drop_index('idx_inv_suc_suc_inv')

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refaccion_definida_por_jefe', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('requiere_aprobacion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aprobacion_estado', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('aprobacion_fecha', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('aprobador_username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('aprobacion_comentario', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estado_cierre', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('motivo_rechazo_cierre', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('motivo_rechazo_cierre')
        batch_op.drop_column('estado_cierre')
        batch_op.drop_column('aprobacion_comentario')
        batch_op.drop_column('aprobador_username')
        batch_op.drop_column('aprobacion_fecha')
        batch_op.drop_column('aprobacion_estado')
        batch_op.drop_column('requiere_aprobacion')
        batch_op.drop_column('refaccion_definida_por_jefe')

    with op.batch_alter_table('inventario_sucursal', schema=None) as batch_op:
        batch_op.create_index('idx_inv_suc_suc_inv', ['sucursal_id', 'inventario_id'], unique=False)

    with op.batch_alter_table('inventario_general', schema=None) as batch_op:
        batch_op.create_index('idx_inv_gen_cat_nombre', ['categoria_inventario_id', 'nombre'], unique=False)

    # ### end Alembic commands ###
