"""seed warehouse commercial catalog

Revision ID: ada9909ac897
Revises: 9dfa6aad20cb
Create Date: 2026-05-20 18:48:37.676711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada9909ac897'
down_revision = '9dfa6aad20cb'
branch_labels = None
depends_on = None


CATALOG_ROWS = [
    # 50% Primer Mes
    {
        "raw_description": "50% 1ER MES 12 MESES $499",
        "normalized_description": "50% 1ER MES 12 MESES $499",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada.",
    },
    {
        "raw_description": "50% 1ER MES 6 MESES $549",
        "normalized_description": "50% 1ER MES 6 MESES $549",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada.",
    },
    {
        "raw_description": "50% 1ER MES SIN PLAZO $599",
        "normalized_description": "50% 1ER MES SIN PLAZO $599",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada.",
    },
    {
        "raw_description": "50% 1ER MES + INSCRIPCIÓN X 12 MESES (TOTAL PRIMER PAGO: $499.50)",
        "normalized_description": "50% 1ER MES + INSCRIPCIÓN X 12 MESES (TOTAL PRIMER PAGO: $499.50)",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada con inscripción.",
    },
    {
        "raw_description": "50% 1ER MES + INSCRIPCIÓN X 6 MESES (TOTAL PRIMER PAGO: $524.50)",
        "normalized_description": "50% 1ER MES + INSCRIPCIÓN X 6 MESES (TOTAL PRIMER PAGO: $524.50)",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada con inscripción.",
    },
    {
        "raw_description": "50% 1ER MES + INSCRIPCIÓN SIN PLAZO (TOTAL PRIMER PAGO: $549.50)",
        "normalized_description": "50% 1ER MES + INSCRIPCIÓN SIN PLAZO (TOTAL PRIMER PAGO: $549.50)",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "descuento_entrada",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo de incentivo de entrada con inscripción.",
    },
    {
        "raw_description": "50% 1ER MES 60+ SIN PLAZO",
        "normalized_description": "50% 1ER MES 60+ SIN PLAZO",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "adulto_mayor",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo 60+.",
    },
    {
        "raw_description": "50% 1ER MES 60+ 6 MESES",
        "normalized_description": "50% 1ER MES 60+ 6 MESES",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "adulto_mayor",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo 60+.",
    },
    {
        "raw_description": "50% 1ER MES 60+ 12 MESES",
        "normalized_description": "50% 1ER MES 60+ 12 MESES",
        "commercial_canon": "50% Primer Mes",
        "family": "incentivo",
        "subfamily": "adulto_mayor",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo 60+.",
    },

    # Borrón y Cuenta Nueva
    {
        "raw_description": "BORRON Y CUENTA NUEVA 12 MESES",
        "normalized_description": "BORRON Y CUENTA NUEVA 12 MESES",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRON Y CUENTA NUEVA 6 MESES",
        "normalized_description": "BORRON Y CUENTA NUEVA 6 MESES",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRON Y CUENTA NUEVA 12 MESES $499",
        "normalized_description": "BORRON Y CUENTA NUEVA 12 MESES $499",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRÓN Y CUENTA NUEVA SIN PLAZO",
        "normalized_description": "BORRÓN Y CUENTA NUEVA SIN PLAZO",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRON 6 MESES PRIMER MES 699 (449 + 250)",
        "normalized_description": "BORRON 6 MESES PRIMER MES 699 (449 + 250)",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRON 12 MESES PRIMER MES $699 (449 + 250)",
        "normalized_description": "BORRON 12 MESES PRIMER MES $699 (449 + 250)",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña de reactivación.",
    },
    {
        "raw_description": "BORRÓN Y CUENTA NUEVA ABRIL",
        "normalized_description": "BORRÓN Y CUENTA NUEVA ABRIL",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si fue campaña temporal de abril o nombre comercial.",
    },
    {
        "raw_description": "BORRÓN Y CUENTA NUEVA MAYO $649",
        "normalized_description": "BORRÓN Y CUENTA NUEVA MAYO $649",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si fue campaña temporal de mayo o nombre comercial.",
    },
    {
        "raw_description": "BORRON Y CUENTA NUEVA HE 12 MESES",
        "normalized_description": "BORRON Y CUENTA NUEVA HE 12 MESES",
        "commercial_canon": "Borrón y Cuenta Nueva",
        "family": "reactivacion",
        "subfamily": "borron_he",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar alcance HE.",
    },

    # TDC
    {
        "raw_description": "BORRON Y CUENTA NUEVA TDC 12 MESES",
        "normalized_description": "BORRON Y CUENTA NUEVA TDC 12 MESES",
        "commercial_canon": "Borrón y Cuenta Nueva TDC",
        "family": "reactivacion",
        "subfamily": "tdc",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Reactivación asociada a TDC.",
    },
    {
        "raw_description": "BORRON Y CUENTA NUEVA TDC 6 MESES",
        "normalized_description": "BORRON Y CUENTA NUEVA TDC 6 MESES",
        "commercial_canon": "Borrón y Cuenta Nueva TDC",
        "family": "reactivacion",
        "subfamily": "tdc",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Reactivación asociada a TDC.",
    },
    {
        "raw_description": "BORRON Y CUENTA NUEVA TDC SIN PLAZO",
        "normalized_description": "BORRON Y CUENTA NUEVA TDC SIN PLAZO",
        "commercial_canon": "Borrón y Cuenta Nueva TDC",
        "family": "reactivacion",
        "subfamily": "tdc",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Reactivación asociada a TDC.",
    },

    # BuenFit / Hot Sale / Preventa
    {
        "raw_description": "DOMICILIADO $449 6 MESES BUENFIT",
        "normalized_description": "DOMICILIADO $449 6 MESES BUENFIT",
        "commercial_canon": "BuenFit",
        "family": "promo_temporal",
        "subfamily": "buenfit",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar periodo/campaña BuenFit.",
    },
    {
        "raw_description": "DOMICILIADO $549 3 MESES BUENFIT",
        "normalized_description": "DOMICILIADO $549 3 MESES BUENFIT",
        "commercial_canon": "BuenFit",
        "family": "promo_temporal",
        "subfamily": "buenfit",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar periodo/campaña BuenFit.",
    },
    {
        "raw_description": "399 HOT SALE",
        "normalized_description": "399 HOT SALE",
        "commercial_canon": "Hot Sale",
        "family": "promo_temporal",
        "subfamily": "hot_sale",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Campaña Hot Sale.",
    },
    {
        "raw_description": "DOMICILIADO 12 MESES $499 PREVENTA",
        "normalized_description": "DOMICILIADO 12 MESES $499 PREVENTA",
        "commercial_canon": "Preventa",
        "family": "preventa",
        "subfamily": "preventa_12m",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Preventa detectada como caso especial.",
    },

    # Primer Mes Gratis
    {
        "raw_description": "DOMICILIADO 1ER MES GRATIS 6 MESES $549",
        "normalized_description": "DOMICILIADO 1ER MES GRATIS 6 MESES $549",
        "commercial_canon": "Primer Mes Gratis",
        "family": "incentivo",
        "subfamily": "primer_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo de entrada.",
    },
    {
        "raw_description": "DOMICILIADO 1ER MES GRATIS 12 MESES $499",
        "normalized_description": "DOMICILIADO 1ER MES GRATIS 12 MESES $499",
        "commercial_canon": "Primer Mes Gratis",
        "family": "incentivo",
        "subfamily": "primer_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo de entrada.",
    },

    # Primer Pago
    {
        "raw_description": "PROMO 399 PRIMER PAGO",
        "normalized_description": "PROMO 399 PRIMER PAGO",
        "commercial_canon": "Primer Pago Promo",
        "family": "incentivo",
        "subfamily": "primer_pago",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo de primer pago.",
    },
    {
        "raw_description": "PROMO 498 PRIMER PAGO",
        "normalized_description": "PROMO 498 PRIMER PAGO",
        "commercial_canon": "Primer Pago Promo",
        "family": "incentivo",
        "subfamily": "primer_pago",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo de primer pago.",
    },
    {
        "raw_description": "PRIMER PAGO 399 POSTERIOR 549",
        "normalized_description": "PRIMER PAGO 399 POSTERIOR 549",
        "commercial_canon": "Primer Pago Promo",
        "family": "incentivo",
        "subfamily": "primer_pago",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo de primer pago.",
    },

    # Temporales por mes/evento
    {
        "raw_description": "PROMO FEBRERO 12 MESES",
        "normalized_description": "PROMO FEBRERO 12 MESES",
        "commercial_canon": "Promo Febrero",
        "family": "promo_temporal",
        "subfamily": "febrero",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si siguió activa después de febrero o si quedó como nombre comercial.",
    },
    {
        "raw_description": "PROMO ENERO 12 MESES",
        "normalized_description": "PROMO ENERO 12 MESES",
        "commercial_canon": "Promo Enero",
        "family": "promo_temporal",
        "subfamily": "enero",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si siguió activa después de enero o si quedó como nombre comercial.",
    },
    {
        "raw_description": "PROMO DICIEMBRE 3 MESES POR $1,350",
        "normalized_description": "PROMO DICIEMBRE 3 MESES POR $1,350",
        "commercial_canon": "Promo Diciembre",
        "family": "promo_temporal",
        "subfamily": "diciembre",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña diciembre.",
    },
    {
        "raw_description": "PROMO MARZO ANTICIPADO $649",
        "normalized_description": "PROMO MARZO ANTICIPADO $649",
        "commercial_canon": "Promo Marzo",
        "family": "promo_temporal",
        "subfamily": "marzo",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar campaña marzo.",
    },

    # Navidad
    {
        "raw_description": "DOMICILIADO NAVIDAD 3 MESES INSCRIPCION GRATIS $549",
        "normalized_description": "DOMICILIADO NAVIDAD 3 MESES INSCRIPCION GRATIS $549",
        "commercial_canon": "Promo Navidad",
        "family": "promo_temporal",
        "subfamily": "navidad",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si es campaña navideña o nombre comercial activo después.",
    },
    {
        "raw_description": "TRIMESTRE NAVIDAD",
        "normalized_description": "TRIMESTRE NAVIDAD",
        "commercial_canon": "Promo Navidad",
        "family": "promo_temporal",
        "subfamily": "navidad",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña navideña.",
    },

    # Noviembre
    {
        "raw_description": "DOMICILIADO 6 MESES PROMO NOVIEMBRE$549",
        "normalized_description": "DOMICILIADO 6 MESES PROMO NOVIEMBRE$549",
        "commercial_canon": "Promo Noviembre",
        "family": "promo_temporal",
        "subfamily": "noviembre",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si siguió activa después de noviembre o quedó como nombre comercial.",
    },
    {
        "raw_description": "DOMICILIADO 12 MESES PROMO NOVIEMBRE $499",
        "normalized_description": "DOMICILIADO 12 MESES PROMO NOVIEMBRE $499",
        "commercial_canon": "Promo Noviembre",
        "family": "promo_temporal",
        "subfamily": "noviembre",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si siguió activa después de noviembre o quedó como nombre comercial.",
    },
    {
        "raw_description": "DOMICILIADO SIN PLAZO PROMO NOVIEMBRE $599",
        "normalized_description": "DOMICILIADO SIN PLAZO PROMO NOVIEMBRE $599",
        "commercial_canon": "Promo Noviembre",
        "family": "promo_temporal",
        "subfamily": "noviembre",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Validar si siguió activa después de noviembre o quedó como nombre comercial.",
    },
    {
        "raw_description": "ESTUDIANTE PROMO NOVIEMBRE $599",
        "normalized_description": "ESTUDIANTE PROMO NOVIEMBRE $599",
        "commercial_canon": "Promo Noviembre",
        "family": "promo_temporal",
        "subfamily": "noviembre_estudiante",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo noviembre estudiante.",
    },
    {
        "raw_description": "CONVENIO PROMO NOVIEMBRE $599",
        "normalized_description": "CONVENIO PROMO NOVIEMBRE $599",
        "commercial_canon": "Promo Noviembre",
        "family": "promo_temporal",
        "subfamily": "noviembre_convenio",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Promo noviembre convenio.",
    },

    # San Valentín
    {
        "raw_description": "PROMO SAN VALENTIN RECURRENTE",
        "normalized_description": "PROMO SAN VALENTIN RECURRENTE",
        "commercial_canon": "Promo San Valentín",
        "family": "promo_temporal",
        "subfamily": "san_valentin",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Aparece en varios meses; validar si es campaña activa o nombre comercial.",
    },
    {
        "raw_description": "12 MESES SAN VALENTÍN PRIMER MES $249.50",
        "normalized_description": "12 MESES SAN VALENTÍN PRIMER MES $249.50",
        "commercial_canon": "Promo San Valentín",
        "family": "promo_temporal",
        "subfamily": "san_valentin",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Campaña San Valentín.",
    },
    {
        "raw_description": "6 MESES SAN VALENTÍN PRIMER MES $274.50",
        "normalized_description": "6 MESES SAN VALENTÍN PRIMER MES $274.50",
        "commercial_canon": "Promo San Valentín",
        "family": "promo_temporal",
        "subfamily": "san_valentin",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Campaña San Valentín.",
    },
    {
        "raw_description": "SAN VALENTÍN PRIMER MES $299.50",
        "normalized_description": "SAN VALENTÍN PRIMER MES $299.50",
        "commercial_canon": "Promo San Valentín",
        "family": "promo_temporal",
        "subfamily": "san_valentin",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": True,
        "notes": "Campaña San Valentín.",
    },

    # Segundo mes gratis
    {
        "raw_description": "DOMICILIADO 12 MESES + 250 INSCRIPCIÓN 2DO MES GRATIS",
        "normalized_description": "DOMICILIADO 12 MESES + 250 INSCRIPCIÓN 2DO MES GRATIS",
        "commercial_canon": "Segundo Mes Gratis",
        "family": "incentivo",
        "subfamily": "segundo_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo segundo mes gratis.",
    },
    {
        "raw_description": "DOMICILIADO 6 MESES + 250 INSCRIPCIÓN 2DO MES GRATIS",
        "normalized_description": "DOMICILIADO 6 MESES + 250 INSCRIPCIÓN 2DO MES GRATIS",
        "commercial_canon": "Segundo Mes Gratis",
        "family": "incentivo",
        "subfamily": "segundo_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo segundo mes gratis.",
    },
    {
        "raw_description": "DOMICILIADO 12 MESES 2DO MES GRATIS",
        "normalized_description": "DOMICILIADO 12 MESES 2DO MES GRATIS",
        "commercial_canon": "Segundo Mes Gratis",
        "family": "incentivo",
        "subfamily": "segundo_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo segundo mes gratis.",
    },
    {
        "raw_description": "DOMICILIADO 6 MESES 2DO MES GRATIS",
        "normalized_description": "DOMICILIADO 6 MESES 2DO MES GRATIS",
        "commercial_canon": "Segundo Mes Gratis",
        "family": "incentivo",
        "subfamily": "segundo_mes_gratis",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Incentivo segundo mes gratis.",
    },

    # Otras campañas
    {
        "raw_description": "PROMO 3 X 2 $1,100",
        "normalized_description": "PROMO 3 X 2 $1,100",
        "commercial_canon": "Promo 3x2",
        "family": "promo_temporal",
        "subfamily": "3x2",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña 3x2.",
    },
    {
        "raw_description": "3 X 2 MESES POR $998",
        "normalized_description": "3 X 2 MESES POR $998",
        "commercial_canon": "Promo 3x2",
        "family": "promo_temporal",
        "subfamily": "3x2",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña 3x2.",
    },
    {
        "raw_description": "3 X 2 MESES POR $1,198 METEPEC",
        "normalized_description": "3 X 2 MESES POR $1,198 METEPEC",
        "commercial_canon": "Promo 3x2",
        "family": "promo_temporal",
        "subfamily": "3x2_metepec",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña 3x2 Metepec.",
    },
    {
        "raw_description": "VENTA ESPECIAL BUEN FIN ANUALIDAD X $3,999",
        "normalized_description": "VENTA ESPECIAL BUEN FIN ANUALIDAD X $3,999",
        "commercial_canon": "Buen Fin",
        "family": "promo_temporal",
        "subfamily": "buen_fin",
        "is_promo": True,
        "is_membership": True,
        "needs_business_validation": False,
        "notes": "Campaña Buen Fin.",
    },
]


def upgrade():
    catalog_table = sa.table(
        "warehouse_commercial_catalog",
        sa.column("raw_description", sa.Text()),
        sa.column("normalized_description", sa.Text()),
        sa.column("commercial_canon", sa.Text()),
        sa.column("family", sa.Text()),
        sa.column("subfamily", sa.Text()),
        sa.column("is_promo", sa.Boolean()),
        sa.column("is_membership", sa.Boolean()),
        sa.column("needs_business_validation", sa.Boolean()),
        sa.column("notes", sa.Text()),
    )

    op.bulk_insert(catalog_table, CATALOG_ROWS)


def downgrade():
    raw_descriptions = [row["raw_description"] for row in CATALOG_ROWS]

    bind = op.get_bind()
    for raw_description in raw_descriptions:
        bind.execute(
            sa.text(
                """
                DELETE FROM warehouse_commercial_catalog
                WHERE raw_description = :raw_description
                """
            ),
            {"raw_description": raw_description},
        )