"""add opening task blockers

Revision ID: db19ee809dba
Revises: 08b732aab9bf
Create Date: 2026-06-09 12:50:23.538603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db19ee809dba'
down_revision = '08b732aab9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opening_task_blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('blocked_task_id', sa.Integer(), nullable=False),
    sa.Column('blocker_type', sa.String(length=32), server_default='OTHER', nullable=False),
    sa.Column('blocking_task_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('impact_level', sa.String(length=20), server_default='MEDIUM', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ACTIVE', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.CheckConstraint('blocking_task_id IS NULL OR blocked_task_id <> blocking_task_id', name='ck_opening_task_blockers_no_self_task'),
    sa.ForeignKeyConstraint(['blocked_task_id'], ['opening_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocking_task_id'], ['opening_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opening_task_blockers', schema=None) as batch_op:
        batch_op.create_index('idx_opening_task_blockers_blocked_status', ['blocked_task_id', 'status'], unique=False)
        batch_op.create_index('idx_opening_task_blockers_opening_status', ['opening_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_blocked_task_id'), ['blocked_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_blocker_type'), ['blocker_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_blocking_task_id'), ['blocking_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_impact_level'), ['impact_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_opening_id'), ['opening_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_resolved_by'), ['resolved_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_blockers_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opening_task_blockers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_status'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_resolved_by'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_opening_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_impact_level'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_created_by'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_created_at'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_blocking_task_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_blocker_type'))
        batch_op.drop_index(batch_op.f('ix_opening_task_blockers_blocked_task_id'))
        batch_op.drop_index('idx_opening_task_blockers_opening_status')
        batch_op.drop_index('idx_opening_task_blockers_blocked_status')

    op.drop_table('opening_task_blockers')
    # ### end Alembic commands ###
