"""add gasca sms requests

Revision ID: e542ba5dfea9
Revises: 7b8c9d0e1f2a
Create Date: 2026-06-27 15:14:48.891804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e542ba5dfea9'
down_revision = '7b8c9d0e1f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gasca_sms_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pin_raw', sa.String(length=32), nullable=False),
    sa.Column('pin_normalized', sa.String(length=5), nullable=False),
    sa.Column('requested_phone_raw', sa.String(length=64), nullable=False),
    sa.Column('requested_phone_digits', sa.String(length=32), nullable=False),
    sa.Column('requested_phone_masked', sa.String(length=32), nullable=False),
    sa.Column('motivo', sa.String(length=80), nullable=False),
    sa.Column('motivo_detalle', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('internal_error', sa.Text(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('gasca_nombre_masked', sa.String(length=180), nullable=True),
    sa.Column('gasca_phone_masked', sa.String(length=32), nullable=True),
    sa.Column('gasca_code_masked', sa.String(length=32), nullable=True),
    sa.Column('gasca_generated_raw', sa.String(length=32), nullable=True),
    sa.Column('gasca_used_raw', sa.String(length=32), nullable=True),
    sa.Column('gasca_sucursal', sa.String(length=120), nullable=True),
    sa.Column('sms_provider', sa.String(length=80), nullable=True),
    sa.Column('sms_message_masked', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gasca_sms_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_pin_normalized'), ['pin_normalized'], unique=False)
        batch_op.create_index('ix_gasca_sms_requests_pin_phone_created_at', ['pin_normalized', 'requested_phone_digits', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_requested_phone_digits'), ['requested_phone_digits'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_status'), ['status'], unique=False)
        batch_op.create_index('ix_gasca_sms_requests_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_gasca_sms_requests_sucursal_created_at', ['sucursal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gasca_sms_requests_sucursal_id'), ['sucursal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gasca_sms_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_sucursal_id'))
        batch_op.drop_index('ix_gasca_sms_requests_sucursal_created_at')
        batch_op.drop_index('ix_gasca_sms_requests_status_created_at')
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_status'))
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_requested_phone_digits'))
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_requested_by_user_id'))
        batch_op.drop_index('ix_gasca_sms_requests_pin_phone_created_at')
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_pin_normalized'))
        batch_op.drop_index(batch_op.f('ix_gasca_sms_requests_created_at'))

    op.drop_table('gasca_sms_requests')
    # ### end Alembic commands ###
