"""add openings base models

Revision ID: f94cb18088cb
Revises: 21d6089a97b9
Create Date: 2026-06-04 10:34:07.219241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94cb18088cb'
down_revision = '21d6089a97b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('opening_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='BORRADOR', nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('target_opening_date', sa.Date(), nullable=True),
    sa.Column('actual_opening_date', sa.Date(), nullable=True),
    sa.Column('general_owner_user_id', sa.Integer(), nullable=True),
    sa.Column('budget_authorized_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_currency_code', sa.String(length=3), server_default='MXN', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['general_owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.sucursal_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.create_index('idx_openings_status_target_date', ['status', 'target_opening_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_general_owner_user_id'), ['general_owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_opening_key'), ['opening_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_openings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_sucursal_id'), ['sucursal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_openings_updated_by'), ['updated_by'], unique=False)

    op.create_table('opening_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('old_value_json', sa.JSON(), nullable=True),
    sa.Column('new_value_json', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opening_audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_opening_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_opening_audit_logs_opening_action', ['opening_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_audit_logs_opening_id'), ['opening_id'], unique=False)

    op.create_table('opening_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='NO_INICIADA', nullable=False),
    sa.Column('owner_department_id', sa.Integer(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_department_id'], ['departamentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opening_id', 'name', name='uq_opening_phases_opening_name')
    )
    with op.batch_alter_table('opening_phases', schema=None) as batch_op:
        batch_op.create_index('idx_opening_phases_opening_order', ['opening_id', 'sort_order'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_opening_id'), ['opening_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_owner_department_id'), ['owner_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_phases_updated_by'), ['updated_by'], unique=False)

    op.create_table('opening_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='NO_INICIADA', nullable=False),
    sa.Column('priority', sa.String(length=20), server_default='MEDIA', nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('owner_department_id', sa.Integer(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_due_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requires_document', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('requires_payment', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_opening_tasks_progress_range'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opening_id'], ['openings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_department_id'], ['departamentos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['opening_tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['phase_id'], ['opening_phases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opening_tasks', schema=None) as batch_op:
        batch_op.create_index('idx_opening_tasks_opening_phase_order', ['opening_id', 'phase_id', 'sort_order'], unique=False)
        batch_op.create_index('idx_opening_tasks_status_due', ['status', 'planned_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_opening_id'), ['opening_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_owner_department_id'), ['owner_department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_parent_task_id'), ['parent_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_phase_id'), ['phase_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_planned_due_date'), ['planned_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_tasks_updated_by'), ['updated_by'], unique=False)

    op.create_table('opening_task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_task_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=32), server_default='BLOCKER', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('task_id <> depends_on_task_id', name='ck_opening_task_dependencies_no_self'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['opening_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['opening_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'depends_on_task_id', name='uq_opening_task_dependencies_pair')
    )
    with op.batch_alter_table('opening_task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opening_task_dependencies_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_dependencies_depends_on_task_id'), ['depends_on_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opening_task_dependencies_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operational_status', sa.String(length=32), server_default='ACTIVA', nullable=False))
        batch_op.create_index(batch_op.f('ix_sucursales_operational_status'), ['operational_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_operational_status'))
        batch_op.drop_column('operational_status')

    with op.batch_alter_table('opening_task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_dependencies_depends_on_task_id'))
        batch_op.drop_index(batch_op.f('ix_opening_task_dependencies_created_by'))

    op.drop_table('opening_task_dependencies')
    with op.batch_alter_table('opening_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_tasks_updated_by'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_title'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_planned_due_date'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_phase_id'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_parent_task_id'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_owner_department_id'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_opening_id'))
        batch_op.drop_index(batch_op.f('ix_opening_tasks_created_by'))
        batch_op.drop_index('idx_opening_tasks_status_due')
        batch_op.drop_index('idx_opening_tasks_opening_phase_order')

    op.drop_table('opening_tasks')
    with op.batch_alter_table('opening_phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_phases_updated_by'))
        batch_op.drop_index(batch_op.f('ix_opening_phases_status'))
        batch_op.drop_index(batch_op.f('ix_opening_phases_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_opening_phases_owner_department_id'))
        batch_op.drop_index(batch_op.f('ix_opening_phases_opening_id'))
        batch_op.drop_index(batch_op.f('ix_opening_phases_created_by'))
        batch_op.drop_index('idx_opening_phases_opening_order')

    op.drop_table('opening_phases')
    with op.batch_alter_table('opening_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_opening_id'))
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_entity_type'))
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_opening_audit_logs_action'))
        batch_op.drop_index('idx_opening_audit_logs_opening_action')
        batch_op.drop_index('idx_opening_audit_logs_entity')

    op.drop_table('opening_audit_logs')
    with op.batch_alter_table('openings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_openings_updated_by'))
        batch_op.drop_index(batch_op.f('ix_openings_sucursal_id'))
        batch_op.drop_index(batch_op.f('ix_openings_status'))
        batch_op.drop_index(batch_op.f('ix_openings_opening_key'))
        batch_op.drop_index(batch_op.f('ix_openings_general_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_openings_created_by'))
        batch_op.drop_index('idx_openings_status_target_date')

    op.drop_table('openings')
    # ### end Alembic commands ###
