"""create marketing iventas persistence tables

Revision ID: fb26a4021f8a
Revises: d5f8a1c2e904
Create Date: 2026-08-08 18:49:24.353275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb26a4021f8a"
down_revision = "d5f8a1c2e904"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "marketing_iventas_sync_runs",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "period_key",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "date_from",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "date_to",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "branches_requested",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "branches_completed",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "branches_failed",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_received",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_unique",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_with_phone",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_mx10_matchable",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_non_mx_or_unresolved",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_with_first_message",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_with_any_tag",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_with_meta_ad_tag",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "contacts_with_multiple_meta_ad_tags",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "aliases_resolved",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "aliases_unresolved",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "is_canonical",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "date_from <= date_to",
            name="ck_marketing_iventas_sync_runs_date_range",
        ),
        sa.CheckConstraint(
            "status IN "
            "('RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED')",
            name="ck_marketing_iventas_sync_runs_status",
        ),
        sa.CheckConstraint(
            "branches_requested >= 0 "
            "AND branches_completed >= 0 "
            "AND branches_failed >= 0 "
            "AND contacts_received >= 0 "
            "AND contacts_unique >= 0 "
            "AND contacts_with_phone >= 0 "
            "AND contacts_mx10_matchable >= 0 "
            "AND contacts_non_mx_or_unresolved >= 0 "
            "AND contacts_with_first_message >= 0 "
            "AND contacts_with_any_tag >= 0 "
            "AND contacts_with_meta_ad_tag >= 0 "
            "AND contacts_with_multiple_meta_ad_tags >= 0 "
            "AND aliases_resolved >= 0 "
            "AND aliases_unresolved >= 0",
            name=(
                "ck_marketing_iventas_sync_runs_"
                "counts_nonnegative"
            ),
        ),
        sa.CheckConstraint(
            "NOT is_canonical "
            "OR ("
            "status = 'COMPLETED' "
            "AND branches_failed = 0 "
            "AND aliases_unresolved = 0"
            ")",
            name=(
                "ck_marketing_iventas_sync_runs_"
                "canonical_valid"
            ),
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_marketing_iventas_sync_runs_is_canonical",
        "marketing_iventas_sync_runs",
        ["is_canonical"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_sync_runs_period_key",
        "marketing_iventas_sync_runs",
        ["period_key"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_sync_runs_status",
        "marketing_iventas_sync_runs",
        ["status"],
        unique=False,
    )

    op.create_table(
        "marketing_iventas_contacts",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "sync_run_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "sucursal_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "branch_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "contact_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "phone_raw",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "phone_digits",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "phone_mx10",
            sa.String(length=10),
            nullable=True,
        ),
        sa.Column(
            "phone_match_status",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "created_at_utc",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at_local",
            sa.DateTime(timezone=False),
            nullable=False,
        ),
        sa.Column(
            "created_date_local",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "first_message_at_utc",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "first_message_at_local",
            sa.DateTime(timezone=False),
            nullable=True,
        ),
        sa.Column(
            "first_message_date_local",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "channel_id",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "channel_name",
            sa.String(length=255),
            nullable=True,
        ),
        sa.Column(
            "channel_phone",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "channel_platform",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "agent_json",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "last_message_status",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "last_outbound_message_at_utc",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "row_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["marketing_iventas_sync_runs.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sucursal_id"],
            ["sucursales.sucursal_id"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sync_run_id",
            "branch_code",
            "contact_id",
            name=(
                "uq_marketing_iventas_contacts_"
                "run_branch_contact"
            ),
        ),
        sa.UniqueConstraint(
            "id",
            "sync_run_id",
            "branch_code",
            "contact_id",
            name=(
                "uq_marketing_iventas_contacts_"
                "row_identity"
            ),
        ),
    )

    op.create_index(
        "ix_marketing_iventas_contacts_branch_code",
        "marketing_iventas_contacts",
        ["branch_code"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_contact_id",
        "marketing_iventas_contacts",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_created_date_local",
        "marketing_iventas_contacts",
        ["created_date_local"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_first_message_date_local",
        "marketing_iventas_contacts",
        ["first_message_date_local"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_phone_mx10",
        "marketing_iventas_contacts",
        ["phone_mx10"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_row_hash",
        "marketing_iventas_contacts",
        ["row_hash"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_sucursal_id",
        "marketing_iventas_contacts",
        ["sucursal_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contacts_sync_run_id",
        "marketing_iventas_contacts",
        ["sync_run_id"],
        unique=False,
    )

    op.create_table(
        "marketing_iventas_raw_pages",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "sync_run_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "branch_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "page_number",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "request_cursor",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "next_cursor",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "has_more",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "http_status",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "payload_json",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "page_number >= 1",
            name=(
                "ck_marketing_iventas_raw_pages_"
                "page_positive"
            ),
        ),
        sa.CheckConstraint(
            "http_status >= 100 AND http_status <= 599",
            name=(
                "ck_marketing_iventas_raw_pages_"
                "http_status"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["marketing_iventas_sync_runs.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sync_run_id",
            "branch_code",
            "page_number",
            name=(
                "uq_marketing_iventas_raw_pages_"
                "run_branch_page"
            ),
        ),
    )

    op.create_index(
        "ix_marketing_iventas_raw_pages_branch_code",
        "marketing_iventas_raw_pages",
        ["branch_code"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_raw_pages_sync_run_id",
        "marketing_iventas_raw_pages",
        ["sync_run_id"],
        unique=False,
    )

    op.create_table(
        "marketing_iventas_contact_tags",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "sync_run_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "iventas_contact_row_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "branch_code",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "contact_id",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "tag_raw",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "tag_kind",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "meta_ad_id",
            sa.String(length=64),
            nullable=True,
        ),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.CheckConstraint(
            "tag_kind IN ('META_AD', 'OTHER')",
            name=(
                "ck_marketing_iventas_contact_tags_kind"
            ),
        ),
        sa.ForeignKeyConstraint(
            [
                "iventas_contact_row_id",
                "sync_run_id",
                "branch_code",
                "contact_id",
            ],
            [
                "marketing_iventas_contacts.id",
                "marketing_iventas_contacts.sync_run_id",
                "marketing_iventas_contacts.branch_code",
                "marketing_iventas_contacts.contact_id",
            ],
            name=(
                "fk_marketing_iventas_contact_tags_"
                "contact_identity"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sync_run_id",
            "iventas_contact_row_id",
            "tag_raw",
            name=(
                "uq_marketing_iventas_contact_tags_"
                "run_contact_tag"
            ),
        ),
    )

    op.create_index(
        "ix_marketing_iventas_contact_tags_contact_id",
        "marketing_iventas_contact_tags",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contact_tags_contact_row_id",
        "marketing_iventas_contact_tags",
        ["iventas_contact_row_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contact_tags_meta_ad_id",
        "marketing_iventas_contact_tags",
        ["meta_ad_id"],
        unique=False,
    )
    op.create_index(
        "ix_marketing_iventas_contact_tags_sync_run_id",
        "marketing_iventas_contact_tags",
        ["sync_run_id"],
        unique=False,
    )


def downgrade():
    op.drop_table(
        "marketing_iventas_contact_tags"
    )
    op.drop_table(
        "marketing_iventas_raw_pages"
    )
    op.drop_table(
        "marketing_iventas_contacts"
    )
    op.drop_table(
        "marketing_iventas_sync_runs"
    )
